CREATE TABLE BOOKS(
isbn VARCHAR NOT NULL PRIMARY KEY,
title VARCHAR NOT NULL,
author VARCHAR NOT NULL,
year INTEGER NOT NULL
);

CREATE TABLE USERS(
email TEXT NOT NULL PRIMARY KEY,
password TEXT NOT NULL
);

CREATE TABLE REVIEWS(
id SERIAL PRIMARY KEY,
rating INTEGER NOT NULL CHECK(rating > 0 and rating <=5),
review TEXT DEFAULT 'No text',
book_isbn VARCHAR NOT NULL REFERENCES BOOKS,
user_email TEXT NOT NULL REFERENCES USERS
);